### PR TITLE
Address several issues discovered in testing

### LINKED ISSUE #17: Large StreamBuffer requests do not block until fulfilled
```
julia> x=read(stream,100000000);
┌ Info: assertion debugging
│   nread = 20072
└   n = 100000000
ERROR: AssertionError: nread == n
Stacktrace:
 [1] read(s::SoapySDR.Stream{ComplexF32}, n::Int64; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ SoapySDR ~/.julia/packages/SoapySDR/ElzKN/src/highlevel.jl:538
 [2] read(s::SoapySDR.Stream{ComplexF32}, n::Int64)
   @ SoapySDR ~/.julia/packages/SoapySDR/ElzKN/src/highlevel.jl:534
 [3] top-level scope
   @ REPL[40]:1
```
Would it make sense to take the requested number of samples as a maximum, and let `read` return less than that?

### PR DESCRIPTION
**Pull request by sjkelly**
- Partially addresses #17 by removing the assert in `read`, and allowing fewer samples as allowed by the semantics of Julia's `read`

- Simplifies the SoapySDR <-> Julia Type pathway. We eliminate the `StreamFormat` container, and just use a few helper functions to keep this abstraction from leaking through the high level API. 

- Constructing a new `Stream` will use the native device format by default (we have multiple dispatch, so we should use it.). It is also now aware of the MTU, thus giving a simplified `read` function without a specified length.

I think this should encapsulate the API changes to address the issues discovered in testing (thanks @mbaz !) I'll need to add some more docs here to full clarify how the `Stream` interface works, mainly regarding `activate!/deactivate!` functions if not using continuous processing. (I'm investigating if we have IO interface semantics in Base for this already)  

re: #17 #13 #12 #8

### CODE REVIEW

File: src/highlevel.jl [hunk 1]
```diff
@@ -543,13 +535,18 @@ Base.length(sb::SampleBuffer) = length(sb.bufs[1])
 function Base.read(s::Stream{T}, n::Int; kwargs...) where {T}
     bufs = ntuple(_->Vector{T}(undef, n), s.nchannels)
     nread, flags, timens = _read!(s, bufs; kwargs...)
-    if nread != n
-        @info("assertion debugging", nread, n)
-        @assert nread == n
-    end
+    # By definition of read, we can allow fewer samples than requested
```
Comment (Keno) [inline src/highlevel.jl:538]: Usually the way that these kinds of IO APIs work in Julia is that they block the task until enough data is available. May or may not be sensible here, but something to think about.

Comment (sjkelly) [reply src/highlevel.jl:538]: I see...
```
  If all is true (the default), this function will block repeatedly trying to read all requested bytes, until an error or
  end-of-file occurs. If all is false, at most one read call is performed, and the amount of data returned is device-dependent.
  Note that not all stream types support the all option.
```
Then we should probably add an `all` kwarg to capture both behaviors.

**Comment by sjkelly** [comment]
I put back the old assertion, with an additional comment in the warning. The main issue can be avoided by `read(...;all=false)`  to allow fewer samples than requested. We will need to block and loop until we fill the requested read amount. May be good to warn if not aligned on the MTU as well. I will track in #17
