### PR TITLE
fix finalizers, closes #3

### LINKED ISSUE #3: KWarg finalizer issue
```
error in running finalizer: MethodError(f=Base.pointer, args=(SoapySDR.OwnedKWArgs(ptr=SoapySDR.SoapySDRKwargs(size=0x0000000000000002, keys=0x0000558ebf9487c0, vals=0x0000558ebf9d0cf0)),), world=0x00000000000073c7)
jl_method_error_bare at /home/steve/Software/julia/src/gf.c:1812
jl_method_error at /home/steve/Software/julia/src/gf.c:1830
jl_lookup_generic_ at /home/steve/Software/julia/src/gf.c:2400 [inlined]
jl_apply_generic at /home/steve/Software/julia/src/gf.c:2415
SoapySDRKwargs_clear at /home/steve/.julia/dev/SoapySDR/src/highlevel.jl:60
jl_apply at /home/steve/Software/julia/src/julia.h:1703 [inlined]
run_finalizer at /home/steve/Software/julia/src/gc.c:278
jl_gc_run_finalizers_in_list at /home/steve/Software/julia/src/gc.c:365
run_finalizers at /home/steve/Software/julia/src/gc.c:394 [inlined]
run_finalizers at /home/steve/Software/julia/src/gc.c:372
jl_atexit_hook at /home/steve/Software/julia/src/init.c:240
repl_entrypoint at /home/steve/Software/julia/src/jlapi.c:703
main at /home/steve/Software/julia/cli/loader_exe.c:51
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
_start at /home/steve/Software/julia/usr/bin/julia (unknown line)
```

### PR DESCRIPTION
**Pull request by sjkelly**

### CODE REVIEW

**Comment by sjkelly** [comment]
Failures related to API issues on Coveralls.

File: src/lowlevel/Types.jl [hunk 1]
```diff
@@ -12,6 +12,11 @@ struct SoapySDRKwargs
     size::Csize_t
     keys::Ptr{Cstring}
     vals::Ptr{Cstring}
+    function SoapySDRKwargs(s,k,v)
+        this = new(s,k,v)
+        finalizer(SoapySDRKwargs_clear, this)
```
Comment (Keno) [inline src/lowlevel/Types.jl:17]: this doesn't work. The struct here has no identity. The finalizer on the mutable struct was correct. Actually, I now realize that it was correct before, because the pointer to the julia object and the pointer to the C object are actually the same (because we inline the C struct by value). My apologies.

Comment (sjkelly) [reply src/lowlevel/Types.jl:17]: Ace. I needed to do some more studying up on this anyway. Thanks for confirming what I was struggling to articulate :) I'll revert 5f8daa0 and this should be good to go?

**Review by Keno — APPROVED** [review]
